---
- name: Create directory for ansible connection plugsins
  file: path=/etc/ansible/connection_plugins state=directory

- name: Get Ansible Connection Plugin to deploy to local lxc containers
  git: repo=https://github.com/Mic92/ansible-lxc dest=/etc/ansible/connection_plugins/lxc
