---
- name: Add ppa repository for ansible-lxc connection plugin
  apt_repository: repo=ppa:hnakamur/ansible-lxc state=present

- name: Install ansible-lxc connection plugin
  apt: name=ansible-lxc state=present
