---
- name: Create dnsmasq hosts config file
  template: src=dnsmasq-hosts.conf.j2 dest=/etc/lxc/dnsmasq-hosts.conf
  register: containers_ipaddr_dnsmasq_hots

- name: Let dnsmasq reload hosts config
  command: killall -SIGHUP dnsmasq
  when: containers_ipaddr_dnsmasq_hots.changed

- name: Stop containers
  lxc_container:
    name: "{{ item.name }}"
    container_log: false
    template: download
    state: stopped
    template_options: -d centos -r 7 -a amd64
  with_items:
    "{{ containers }}"
  when: containers_ipaddr_dnsmasq_hots.changed
  tags: [stop_containers]

- name: Create and start containers
  lxc_container:
    name: "{{ item.name }}"
    container_log: true
    template: download
    state: started
    template_options: -d centos -r 7 -a amd64
  with_items:
    "{{ containers }}"
